# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      # Set up a matrix to run the following 3 configurations:
      # 1. <Windows, Release, latest MSVC compiler toolchain on the default runner image, default generator>
      # 2. <Linux, Release, latest GCC compiler toolchain on the default runner image, default generator>
      # 3. <Linux, Release, latest Clang compiler toolchain on the default runner image, default generator>
      #
      # To add more build types (Release, Debug, RelWithDebInfo, etc.) customize the build_type list.
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            preset: windows-build
            name: Release/WebCraft.exe
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            preset: linux-build
            name: WebCraft
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
            preset: linux-build
            name: WebCraft
          - os: macos-latest
            c_compiler: /opt/homebrew/opt/gcc/bin/gcc
            cpp_compiler: /opt/homebrew/opt/gcc/bin/g++
            preset: macos-build
            name: WebCraft
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
            preset: macos-build
            name: WebCraft
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl
          - os: macos-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        
    - name: Get Version of Compiler which is not Windows
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        echo "C Compiler: ${{ matrix.c_compiler }}"
        echo "C++ Compiler: ${{ matrix.cpp_compiler }}"

    - name: Setup Homebrew for MacOS
      if: ${{ matrix.os == 'macos-latest' }}
      id: setup_homebrew
      uses: Homebrew/actions/setup-homebrew@master    

    - name: Configure CMake not for MacOS
      if: ${{ ! (matrix.os == 'macos-latest' && matrix.c_compiler == 'clang') }}
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: >
        cmake
        --preset=${{ matrix.preset }}
        -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}
    
    - name: Configure CMake for MacOS
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        if [[ ${{ matrix.c_compiler }} == 'clang' ]]; then
          cmake \
          --preset=${{ matrix.preset }} \
          -B ${{ steps.strings.outputs.build-output-dir }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
          -S ${{ github.workspace }}
        else
          brew install gcc
          echo "C Compiler: gcc-15"
          echo "C++ Compiler: g++-15"
          echo "CC=$(brew --prefix gcc)/bin/gcc" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix gcc)/bin/g++" >> $GITHUB_ENV
          cmake \
          --preset=${{ matrix.preset }} \
          -B ${{ steps.strings.outputs.build-output-dir }} \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -S ${{ github.workspace }}
        fi

    - name: Build not for MacOS
      if: ${{ matrix.os != 'macos-latest' }}
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Build for MacOS
      if: ${{ matrix.os == 'macos-latest' && matrix.c_compiler == 'clang' }}
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }}

    - name: Run the executable
      # Run the executable that was built. The executable name is assumed to be 'my_executable' in this example.
      run: ${{ steps.strings.outputs.build-output-dir }}/${{ matrix.name }}

    # - name: Test
    #   working-directory: ${{ steps.strings.outputs.build-output-dir }}
    #   # Execute tests defined by the CMake configuration. Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
    #   # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #   run: ctest --build-config ${{ matrix.build_type }}
